# Generated by Django 2.1.5 on 2019-02-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=60)),
                ('origin', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=120)),
                ('recipient', models.CharField(max_length=100)),
                ('recipient_phone', models.IntegerField()),
                ('sender_phone', models.IntegerField()),
            ],
        ),
    ]
