# Generated by Django 2.1.7 on 2019-02-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_phone', models.IntegerField(max_length=15)),
                ('operation_area', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
