# Generated by Django 2.1.7 on 2019-02-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='contact_phone',
            field=models.IntegerField(),
        ),
    ]
